# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-18 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', multiselectfield.db.fields.MultiSelectField(choices=[('maharashtra', 'maharashtra'), ('hariyana', 'hariyana'), ('chattisgarh', 'chattisgarh'), ('karnataka', 'karnataka')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('location', models.TextField(max_length=200)),
                ('offer_price', models.CharField(max_length=10)),
                ('availability', models.BooleanField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(null=True, upload_to=b'')),
                ('join_date', models.DateTimeField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.contact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.location')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
    ]
